# Permalinks
permalink:           pretty

# Setup
title:               jpctan - Jason Tan
tagline:             AI is the baseline
description:         >
  tba 
url:                 "https://jpctan.github.io"
paginate:            5
baseurl:             ""

# Assets
sass:
  style:            :compressed

# About/contact
author:
  name:              Jason Tan
  url:               https://jpctan.github.io
  email:             jasontpc@gmail.com

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/poole/hyde

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
